# Mapping: tên file (không có extension) -> metadata đầy đủ
DOCUMENT_METADATA = {

    # ── NHÓM 1: ĐẠO LUẬT NỀN TẢNG ──────────────────────────────────────
    "luat_cntt_2006_vbhn_2023": {
        "ten_van_ban": "Luật Công nghệ thông tin 2006",
        "so_hieu": "67/2006/QH11",
        "so_vbhn": "39/VBHN-VPQH",
        "loai_van_ban": "Luật",
        "co_quan_ban_hanh": "Quốc hội",
        "ngay_ban_hanh": "29/06/2006",
        "ngay_hieu_luc": "01/01/2007",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": "Luật Quy hoạch 21/2017/QH14; Luật GDĐT 20/2023/QH15; Luật Viễn thông 24/2023/QH15",
        "ban_su_dung": "VBHN 39/VBHN-VPQH ngày 27/12/2023",
        "nhom": "Nhóm 1 - Đạo luật nền tảng",
        "ghi_chu": "VBHN tích hợp 3 lần sửa đổi",
    },
    "luat_attt_mang_2015_vbhn_2018": {
        "ten_van_ban": "Luật An toàn thông tin mạng 2015",
        "so_hieu": "86/2015/QH13",
        "so_vbhn": "VBHN 2018",
        "loai_van_ban": "Luật",
        "co_quan_ban_hanh": "Quốc hội",
        "ngay_ban_hanh": "19/11/2015",
        "ngay_hieu_luc": "01/07/2016",
        "ngay_het_hieu_luc": "30/06/2026",
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": "Luật 35/2018/QH14",
        "ban_su_dung": "VBHN 2018",
        "nhom": "Nhóm 1 - Đạo luật nền tảng",
        "ghi_chu": "Hết hiệu lực 30/6/2026 khi Luật ANM 2025 có hiệu lực",
    },
    "luat_an_ninh_mang_2018": {
        "ten_van_ban": "Luật An ninh mạng 2018",
        "so_hieu": "24/2018/QH14",
        "so_vbhn": None,
        "loai_van_ban": "Luật",
        "co_quan_ban_hanh": "Quốc hội",
        "ngay_ban_hanh": "12/06/2018",
        "ngay_hieu_luc": "01/01/2019",
        "ngay_het_hieu_luc": "30/06/2026",
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc 24/2018/QH14",
        "nhom": "Nhóm 1 - Đạo luật nền tảng",
        "ghi_chu": "Hết hiệu lực 30/6/2026 khi Luật ANM 2025 (116/2025/QH15) có hiệu lực",
    },
    "luat_an_ninh_mang_2025": {
        "ten_van_ban": "Luật An ninh mạng 2025",
        "so_hieu": "116/2025/QH15",
        "so_vbhn": None,
        "loai_van_ban": "Luật",
        "co_quan_ban_hanh": "Quốc hội",
        "ngay_ban_hanh": "10/12/2025",
        "ngay_hieu_luc": "01/07/2026",
        "ngay_het_hieu_luc": None,
        "trang_thai": "chua_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc 116/2025/QH15",
        "nhom": "Nhóm 1 - Đạo luật nền tảng",
        "ghi_chu": "Hợp nhất và bãi bỏ Luật ATTT mạng 2015 + Luật ANM 2018",
    },
    "luat_giao_dich_dien_tu_2023": {
        "ten_van_ban": "Luật Giao dịch điện tử 2023",
        "so_hieu": "20/2023/QH15",
        "so_vbhn": None,
        "loai_van_ban": "Luật",
        "co_quan_ban_hanh": "Quốc hội",
        "ngay_ban_hanh": "22/06/2023",
        "ngay_hieu_luc": "01/07/2024",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": "Một số điều sửa đổi bởi Luật Dữ liệu 60/2024/QH15",
        "ban_su_dung": "Bản gốc 20/2023/QH15",
        "nhom": "Nhóm 1 - Đạo luật nền tảng",
        "ghi_chu": None,
    },
    "luat_vien_thong_2023": {
        "ten_van_ban": "Luật Viễn thông 2023",
        "so_hieu": "24/2023/QH15",
        "so_vbhn": None,
        "loai_van_ban": "Luật",
        "co_quan_ban_hanh": "Quốc hội",
        "ngay_ban_hanh": "24/11/2023",
        "ngay_hieu_luc": "01/07/2024",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc 24/2023/QH15",
        "nhom": "Nhóm 1 - Đạo luật nền tảng",
        "ghi_chu": None,
    },
    "luat_shtt_2005_vbhn_2022": {
        "ten_van_ban": "Luật Sở hữu trí tuệ 2005",
        "so_hieu": "50/2005/QH11",
        "so_vbhn": "VBHN 2022",
        "loai_van_ban": "Luật",
        "co_quan_ban_hanh": "Quốc hội",
        "ngay_ban_hanh": "29/11/2005",
        "ngay_hieu_luc": "01/07/2006",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": "Luật 36/2009/QH12; Luật 42/2019/QH14; Luật 07/2022/QH15",
        "ban_su_dung": "VBHN 2022",
        "nhom": "Nhóm 1 - Đạo luật nền tảng",
        "ghi_chu": None,
    },
    "luat_du_lieu_2024": {
        "ten_van_ban": "Luật Dữ liệu 2024",
        "so_hieu": "60/2024/QH15",
        "so_vbhn": None,
        "loai_van_ban": "Luật",
        "co_quan_ban_hanh": "Quốc hội",
        "ngay_ban_hanh": "30/11/2024",
        "ngay_hieu_luc": "01/07/2025",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc 60/2024/QH15",
        "nhom": "Nhóm 1 - Đạo luật nền tảng",
        "ghi_chu": "Luật chuyên biệt đầu tiên về dữ liệu số tại VN",
    },
    "luat_bvdlcn_2025": {
        "ten_van_ban": "Luật Bảo vệ dữ liệu cá nhân 2025",
        "so_hieu": "91/2025/QH15",
        "so_vbhn": None,
        "loai_van_ban": "Luật",
        "co_quan_ban_hanh": "Quốc hội",
        "ngay_ban_hanh": "26/06/2025",
        "ngay_hieu_luc": "01/01/2026",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc 91/2025/QH15",
        "nhom": "Nhóm 1 - Đạo luật nền tảng",
        "ghi_chu": "Thay thế về thực chất NĐ 13/2023/NĐ-CP",
    },
    "luat_cnts_2025": {
        "ten_van_ban": "Luật Công nghiệp công nghệ số 2025",
        "so_hieu": "71/2025/QH15",
        "so_vbhn": None,
        "loai_van_ban": "Luật",
        "co_quan_ban_hanh": "Quốc hội",
        "ngay_ban_hanh": "14/06/2025",
        "ngay_hieu_luc": "01/01/2026",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc 71/2025/QH15",
        "nhom": "Nhóm 1 - Đạo luật nền tảng",
        "ghi_chu": "Quy định bán dẫn, AI, tài sản số. Một số điều hiệu lực từ 01/7/2025",
    },
    "luat_bvqlntd_2023": {
        "ten_van_ban": "Luật Bảo vệ quyền lợi người tiêu dùng 2023",
        "so_hieu": "19/2023/QH15",
        "so_vbhn": None,
        "loai_van_ban": "Luật",
        "co_quan_ban_hanh": "Quốc hội",
        "ngay_ban_hanh": "20/06/2023",
        "ngay_hieu_luc": "01/07/2024",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc 19/2023/QH15 - Tập trung Chương III",
        "nhom": "Nhóm 1 - Đạo luật nền tảng",
        "ghi_chu": "Khai thác Chương III: Giao dịch trên không gian mạng",
    },

    # ── NHÓM 2: NGHỊ ĐỊNH ───────────────────────────────────────────────
    "nd_71_2007": {
        "ten_van_ban": "Nghị định về công nghiệp công nghệ thông tin",
        "so_hieu": "71/2007/NĐ-CP",
        "so_vbhn": None,
        "loai_van_ban": "Nghị định",
        "co_quan_ban_hanh": "Chính phủ",
        "ngay_ban_hanh": "03/05/2007",
        "ngay_hieu_luc": "25/05/2007",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc NĐ 71/2007/NĐ-CP",
        "nhom": "Nhóm 2 - Nghị định",
        "ghi_chu": "Nhiều điều lạc hậu, chờ NĐ hướng dẫn Luật 71/2025/QH15 thay thế",
    },
    "nd_85_2016": {
        "ten_van_ban": "Nghị định về bảo đảm an toàn hệ thống thông tin theo cấp độ",
        "so_hieu": "85/2016/NĐ-CP",
        "so_vbhn": None,
        "loai_van_ban": "Nghị định",
        "co_quan_ban_hanh": "Chính phủ",
        "ngay_ban_hanh": "01/07/2016",
        "ngay_hieu_luc": "15/08/2016",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc NĐ 85/2016/NĐ-CP",
        "nhom": "Nhóm 2 - Nghị định",
        "ghi_chu": "Sẽ điều chỉnh theo Luật ANM 2025 sau 01/7/2026",
    },
    "nd_130_2018": {
        "ten_van_ban": "Nghị định về chữ ký số và dịch vụ tin cậy",
        "so_hieu": "130/2018/NĐ-CP",
        "so_vbhn": None,
        "loai_van_ban": "Nghị định",
        "co_quan_ban_hanh": "Chính phủ",
        "ngay_ban_hanh": "27/09/2018",
        "ngay_hieu_luc": "15/11/2018",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc NĐ 130/2018/NĐ-CP",
        "nhom": "Nhóm 2 - Nghị định",
        "ghi_chu": None,
    },
    "nd_53_2022": {
        "ten_van_ban": "Nghị định quy định chi tiết Luật An ninh mạng 2018",
        "so_hieu": "53/2022/NĐ-CP",
        "so_vbhn": None,
        "loai_van_ban": "Nghị định",
        "co_quan_ban_hanh": "Chính phủ",
        "ngay_ban_hanh": "15/08/2022",
        "ngay_hieu_luc": "01/10/2022",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc NĐ 53/2022/NĐ-CP",
        "nhom": "Nhóm 2 - Nghị định",
        "ghi_chu": "Chờ thay thế sau khi Luật ANM 2025 có hiệu lực 01/7/2026",
    },
    "nd_13_2023": {
        "ten_van_ban": "Nghị định về bảo vệ dữ liệu cá nhân",
        "so_hieu": "13/2023/NĐ-CP",
        "so_vbhn": None,
        "loai_van_ban": "Nghị định",
        "co_quan_ban_hanh": "Chính phủ",
        "ngay_ban_hanh": "17/04/2023",
        "ngay_hieu_luc": "01/07/2023",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc NĐ 13/2023/NĐ-CP",
        "nhom": "Nhóm 2 - Nghị định",
        "ghi_chu": "Áp dụng song song với Luật 91/2025/QH15. Phần mâu thuẫn thì ưu tiên Luật",
    },
    "nd_15_2020_vbhn": {
        "ten_van_ban": "Nghị định xử phạt vi phạm hành chính lĩnh vực bưu chính, viễn thông, CNTT",
        "so_hieu": "15/2020/NĐ-CP",
        "so_vbhn": None,
        "loai_van_ban": "Nghị định",
        "co_quan_ban_hanh": "Chính phủ",
        "ngay_ban_hanh": "03/02/2020",
        "ngay_hieu_luc": "15/04/2020",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": "NĐ 14/2022/NĐ-CP; NĐ 211/2025/NĐ-CP",
        "ban_su_dung": "NĐ 15/2020 + NĐ 14/2022 + NĐ 211/2025 (tải riêng)",
        "nhom": "Nhóm 2 - Nghị định",
        "ghi_chu": "Chuỗi: NĐ 15/2020 → sửa đổi bởi NĐ 14/2022 → NĐ 211/2025",
    },
    "nd_147_2024": {
        "ten_van_ban": "Nghị định quản lý, cung cấp, sử dụng dịch vụ Internet và thông tin trên mạng",
        "so_hieu": "147/2024/NĐ-CP",
        "so_vbhn": None,
        "loai_van_ban": "Nghị định",
        "co_quan_ban_hanh": "Chính phủ",
        "ngay_ban_hanh": "09/11/2024",
        "ngay_hieu_luc": "25/12/2024",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc NĐ 147/2024/NĐ-CP",
        "nhom": "Nhóm 2 - Nghị định",
        "ghi_chu": "Thay thế NĐ 72/2013 và các VBHN cũ",
    },
    "nd_52_2013_vbhn_14_bct": {
        "ten_van_ban": "Nghị định về thương mại điện tử",
        "so_hieu": "52/2013/NĐ-CP",
        "so_vbhn": "14/VBHN-BCT",
        "loai_van_ban": "Nghị định",
        "co_quan_ban_hanh": "Chính phủ",
        "ngay_ban_hanh": "16/05/2013",
        "ngay_hieu_luc": "01/07/2013",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": "NĐ 08/2018/NĐ-CP; NĐ 85/2021/NĐ-CP",
        "ban_su_dung": "VBHN 14/VBHN-BCT ngày 19/11/2021 (Bộ Công Thương)",
        "nhom": "Nhóm 2 - Nghị định",
        "ghi_chu": "Dùng VBHN 14/VBHN-BCT vì cơ quan nhà nước ban hành, chuỗi sửa đổi đã đóng",
    },
    "nd_17_2023": {
        "ten_van_ban": "Nghị định quy định chi tiết Luật SHTT về quyền tác giả, phần mềm máy tính",
        "so_hieu": "17/2023/NĐ-CP",
        "so_vbhn": None,
        "loai_van_ban": "Nghị định",
        "co_quan_ban_hanh": "Chính phủ",
        "ngay_ban_hanh": "26/04/2023",
        "ngay_hieu_luc": "26/04/2023",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc NĐ 17/2023/NĐ-CP",
        "nhom": "Nhóm 2 - Nghị định",
        "ghi_chu": None,
    },
    "nd_52_2024": {
        "ten_van_ban": "Nghị định về thanh toán không dùng tiền mặt",
        "so_hieu": "52/2024/NĐ-CP",
        "so_vbhn": None,
        "loai_van_ban": "Nghị định",
        "co_quan_ban_hanh": "Chính phủ",
        "ngay_ban_hanh": "15/05/2024",
        "ngay_hieu_luc": "01/07/2024",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc NĐ 52/2024/NĐ-CP",
        "nhom": "Nhóm 2 - Nghị định",
        "ghi_chu": "Thay thế NĐ 101/2012",
    },
    "nd_211_2025": {
        "ten_van_ban": "Nghị định về hoạt động mật mã dân sự và sửa đổi NĐ 15/2020",
        "so_hieu": "211/2025/NĐ-CP",
        "so_vbhn": None,
        "loai_van_ban": "Nghị định",
        "co_quan_ban_hanh": "Chính phủ",
        "ngay_ban_hanh": "25/07/2025",
        "ngay_hieu_luc": "18/06/2025",
        "ngay_het_hieu_luc": None,
        "trang_thai": "con_hieu_luc",
        "sua_doi_boi": None,
        "ban_su_dung": "Bản gốc NĐ 211/2025/NĐ-CP",
        "nhom": "Nhóm 2 - Nghị định",
        "ghi_chu": "Quy định mật mã dân sự + sửa đổi NĐ 15/2020",
    },
}

# Fuzzy matching: từ khóa trong tên file -> key trong DOCUMENT_METADATA
FILENAME_KEYWORDS = {
    # Nhóm Luật
    "luật cntt 2006": "luat_cntt_2006_vbhn_2023",
    "luật attt mạng 2015": "luat_attt_mang_2015_vbhn_2018",
    "luật an ninh mạng 2018": "luat_an_ninh_mang_2018",
    "luật an ninh mạng 2025": "luat_an_ninh_mang_2025",
    "luật giao dịch điện tử 2023": "luat_giao_dich_dien_tu_2023",
    "luật viễn thông 2023": "luat_vien_thong_2023",
    "luật sở hữu trí tuệ 2005": "luat_shtt_2005_vbhn_2022",
    "luật dữ liệu 2024": "luat_du_lieu_2024",
    "luật bảo vệ dữ liệu cá nhân 2025": "luat_bvdlcn_2025",
    "luật công nghiệp công nghệ số 2025": "luat_cnts_2025",
    "luật bảo vệ quyền lợi người tiêu dùng 2023": "luat_bvqlntd_2023",
    
    # Nhóm Nghị định
    "nghị định 71 2007": "nd_71_2007",
    "nghị định 85 2016": "nd_85_2016",
    "nghị định 130 2018": "nd_130_2018",
    "nghị định 53 2022": "nd_53_2022",
    "nghị định 13 2023": "nd_13_2023",
    "nghị định 15 2020": "nd_15_2020_vbhn",
    "nghị định 147 2024": "nd_147_2024",
    "nghị định 52 2013": "nd_52_2013_vbhn_14_bct",
    "nghị định 17 2023": "nd_17_2023",
    "nghị định 52 2024": "nd_52_2024",
    "nghị định 211 2025": "nd_211_2025",
}